In [6]:
import numpy as x
p= x.array([[1,2,3,4,5],[7,8,9,6,0]])
print(p)


[[1 2 3 4 5]
 [7 8 9 6 0]]


In [9]:
app = x.array([1,2,3,4,5],ndmin = 10)
print(app)
print(app.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [7]:
arr=x.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
