Initial Placeholders in numpy arrays

In [1]:
#create ab numpy array for zeros
import numpy as k
j=k.zeros((4,5))
print(j)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
#create a numpy arrays of ones
y=k.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#create an array of a particualr value
z=k.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [5]:
#create an identity matrix
i =k.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#create an numpy array with random values
r = k.random.random((3,4))
print(r)

[[0.52643168 0.70814709 0.13346474 0.66733313]
 [0.95469986 0.8721081  0.55748669 0.16010688]
 [0.02193178 0.23621399 0.62438079 0.07509609]]


In [14]:
#create an random integer values array with a specific range
ri = k.random.randint(10,30,(3,4))
print(ri)

[[10 20 10 28]
 [21 16 10 21]
 [25 27 14 21]]


In [20]:
#create an array of evenly spaced values
d = k.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [22]:
#array of evenly spaced values -->specifining the step
s=k.arange(10,30,6)
print(s)

[10 16 22 28]


In [24]:
#convert a list to a numpy array
list2=[1,2,3,4,5,6]
k_array=k.array(list2)
print(k_array)
type(k_array)

[1 2 3 4 5 6]


numpy.ndarray

analysing a perticular array

In [25]:
g= k.random.randint(10,90,(5,5))
print(g)

[[29 14 42 39 57]
 [13 72 74 24 34]
 [60 82 46 75 18]
 [14 80 37 36 18]
 [46 61 32 31 59]]


In [27]:
print(g.shape)#shape
print(g.ndim)#dimention
print(g.size)#number of elements
print(g.dtype)#deta type of element

(5, 5)
2
25
int32


Mathamatical operation on numpy array

In [40]:
list3=[3,4,5,6]
list4=[7,8,9,10]
print(list3+list4)
rn=k.random.randint(0,10,(3,3))
rnn=k.random.randint(10,20,(3,3))
print(rn)
print(rnn)
print(k.add(rn,rnn))
print(k.multiply(rn,rnn))
print(k.divide(rn,rnn))

[3, 4, 5, 6, 7, 8, 9, 10]
[[3 3 5]
 [8 3 4]
 [1 0 1]]
[[15 17 13]
 [16 18 18]
 [13 18 10]]
[[18 20 18]
 [24 21 22]
 [14 18 11]]
[[ 45  51  65]
 [128  54  72]
 [ 13   0  10]]
[[0.2        0.17647059 0.38461538]
 [0.5        0.16666667 0.22222222]
 [0.07692308 0.         0.1       ]]
